language: php
dist: trusty
addons:
  chrome: stable
matrix:
  include:
    - php: 7.1
    - php: 7.2
before_install:
  - google-chrome-stable --version
  - google-chrome-stable --headless --no-gpu --disable-gpu --no-sandbox --remote-debugging-port=9222 &
install:
  - composer install --no-interaction
script:
  - vendor/bin/phpunit